export default {
  // USER
  LOGIN: "LOGIN",
  LOGIN_ERR: "LOGIN_ERR",
  REGISTER: "REGISTER",
  REGISTER_ERR: "REGISTER_ERR",
  UPDATE: "UPDATE",
  UPDATE_ERR: "UPDATE_ERR",
  DEACTIVATE_ACCOUNT: "DEACTIVATE_ACCOUNT",
  DEACTIVATE_ACCOUNT_ERR: "DEACTIVATE_ACCOUNT_ERR",
  VERIFY_ME: "VERIFY_ME"
};
