export default {
  // USER
  LOGIN: "LOGIN",
  LOGIN_ERR: "LOGIN_ERR",
  REGISTER: "REGISTER",
  REGISTER_ERR: "REGISTER_ERR",
  UPDATE: "UPDATE",
  UPDATE_ERR: "UPDATE_ERR",
  DEACTIVATE_ACCOUNT: "DEACTIVATE_ACCOUNT",
  DEACTIVATE_ACCOUNT_ERR: "DEACTIVATE_ACCOUNT_ERR",
  VERIFY_ME: "VERIFY_ME",

  // Gallery
  GET_IMAGE: "GET_IMAGE",
  GET_ALL_IMAGES: "GET_ALL_IMAGES",
  ADD_IMAGE: "ADD_IMAGE",
  UPDATE_IMAGE: "UPDATE_IMAGE",
  DELETE_IMAGE: "DELETE_IMAGE"
};
