export default {
  // * USER
  LOGIN: "LOGIN",
  LOGIN_FAILED: "LOGIN_FAILED",
  REGISTER: "REGISTER",
  REGISTER_FAILED: "REGISTER_FAILED",
  UPDATE_USER: "UPDATE_USER",
  UPDATE_FAILED: "UPDATE_FAILED",
  DEACTIVATE_ACCOUNT: "DEACTIVATE_ACCOUNT",
  DEACTIVATE_ACCOUNT_FAILED: "DEACTIVATE_ACCOUNT_FAILED",
  VERIFY_ME: "VERIFY_ME",
  VERIFY_ME_FAILED: "VERIFY_ME_FAILED",

  // * Gallery
  GET_IMAGE: "GET_IMAGE",
  GET_IMAGE_FAILED: "GET_IMAGE_FAILED",
  GET_ALL_IMAGES: "GET_ALL_IMAGES",
  GET_ALL_IMAGES_FAILED: "GET_ALL_IMAGES_FAILED",
  ADD_IMAGE: "ADD_IMAGE",
  ADD_IMAGE_FAILED: "ADD_IMAGE_FAILED",
  UPDATE_IMAGE: "UPDATE_IMAGE",
  UPDATE_IMAGE_FAILED: "UPDATE_IMAGE_FAILED",
  DELETE_IMAGE: "DELETE_IMAGE",
  DELETE_IMAGE_FAILED: "DELETE_IMAGE_FAILED"
};
